eshopper/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login,logout

from . import views

app_name = 'eshopper'

urlpatterns = [
	# url(r'^$', views.home, name='home'),
	url(r'^signup/$', views.signup, name='signup'),
	url(r'^login/$',login, name='login',kwargs={
		'template_name': 'eshopper/search.html'}),
	url(r'^logout/$',logout,name='logout',kwargs={'next_page': '/'}),
	url(r'^apply/$', views.coupon_apply, name='apply'),
	url(r'^remove/$', views.coupon_remove, name='coupon_remove'),
	url(r'^cart/$', views.cart_detail, name='cart_detail'),
	url(r'^cart/add/(?P<product_id>\d+)/$', views.cart_add, 
		name='cart_add'),
	url(r'^cart/remove/(?P<product_id>\d+)/$', views.cart_remove, 
		name='cart_remove'),
	url(r'^orders/$', views.order_create, name='order_create'),
	url(r'^$', views.product_list, name='product_list'),
	url(r'^products/(?P<category_slug>[-\w]+)/$', views.product_list, 
		name='product_list_by_category'),
	url(r'^products/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, 
		name='product_detail'),
	url(r'^contact/$', views.contact, name='contact'),
	url(r'^search/?$', views.search, name='search'),
	# url(r'^wishlist/(?P<id>\d+)/$', views.add_userwl, name='add_userwl'),


]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
	url(r'^paypal/', include('paypal.standard.ipn.urls')),
	url(r'^payment/', include('payment.urls')),
	url(r'', include('eshopper.urls')),
	url(r'^oauth/', include('social_django.urls', namespace='social')),
	url(r'^admin/', admin.site.urls),
]


if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eshopper/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import User_address, Contact_us, User_order, Product, Coupon
from ckeditor.widgets import CKEditorWidget
from ckeditor.fields import RichTextField



class SignupForm(UserCreationForm):
	
	class Meta:
		model = User 
		fields = ['username', 'email', 'password1', 
				  'password2']

	def clean_confirm_password(self):
		
		password = self.cleaned_data['password1']
		confirm_password = self.cleaned_data['password2']
		
		if password and confirm_password and password != confirm_password:
			raise forms.ValidationError("password do not match.")
		return confirm_password

	def clean_username(self):
		
		username = self.cleaned_data['username']

		try:
			User.objects.get(username=username)
		except User.DoesNotExist:
			return username	
		raise forms.ValidationError("Username is already taken.")	
		
	def save(self, commit=True):
		
		user = super(SignupForm, self).save(commit)
		user.set_password(self.cleaned_data['password1'])
		if commit:
			user.save()
		return user 			





# PRODUCT_QUANTITY_CHOICE = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
	quantity = forms.CharField(required=True,widget=forms.TextInput(attrs={'class':'form-control' , 'autocomplete': 'off','pattern':'[0-9]+'}))
	# quantity = forms.TextInput(coerce=int)
	update = forms.BooleanField(required=False, initial=False, 
								widget=forms.HiddenInput)	


class ContactForm(forms.ModelForm):
	message = forms.CharField(widget=CKEditorWidget())
	class Meta:
		model = Contact_us
		fields = ['name', 'email', 'message']
		widgets = {'name' :forms.TextInput(attrs={'class':'form-control',
				   'placeholder':'name'}),
				   'email':forms.EmailInput(attrs={'class':'form-control',
				   'placeholder':'email'}),
			    #    'message' :forms.Textarea(attrs={'class':'form-control', 
				   # 'placeholder':'Type your message here'}),
		}


class OrderCreateForm(forms.ModelForm):
	
	class Meta:
		model = User_order
		fields = ['address', 'city', 'state', 'country', 'zipcode', 'message']
		widgets = {'address' :forms.TextInput(attrs={'class':'form-control',
				   'placeholder':'address'}),
				   'city':forms.TextInput(attrs={'class':'form-control',
				   'placeholder':'city'}),
			       'state' :forms.TextInput(attrs={'class':'form-control', 
				   'placeholder':'state'}),
				   'country' :forms.TextInput(attrs={'class':'form-control',
				   'placeholder':'country'}),
				   'zipcode':forms.TextInput(attrs={'class':'form-control',
				   'placeholder':'zipcode'}),
			       'message' :forms.Textarea(attrs={'class':'form-control', 
				   'placeholder':'Notes about your order, Special Notes for Delivery'}),
		}

class CouponApplyForm(forms.Form):
	
	code = forms.CharField(max_length=255)

	def clean_code(self):
		code = self.cleaned_data['code']

		if Coupon.objects.filter(code=code):
			return code

		raise forms.ValidationError("Coupon code Does not exist.")	

eshopper/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django import forms
from .models import  Coupon, Category, Product, Order_details,Email_template, User_wish_list
from .cart import Cart
from .forms import *
from django.core.urlresolvers import reverse
from django.core.mail import EmailMessage
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.template  import Context, Template
from django.contrib import messages
from django.utils import timezone
# Create your views here.

def home(request):
	
	return render(request, 'eshopper/home.html')

# def signup(request):
	
# 	if request.method == 'POST':
# 		form = SignupForm(request.POST)
# 		if form.is_valid():
			
# 			username = form.cleaned_data['username']
# 			email = form.cleaned_data['email']
# 			password = form.cleaned_data['password1']
# 			user = User(username=username, email=email)
# 			user.set_password(password)
# 			user.save()
			
# 			current_site = get_current_site(request)
# 			mail_template = Email_template.objects.get(title='Registration')
# 			message = Template(mail_template.content)
			
# 			to_mail = form.cleaned_data.get('email')
# 			email = EmailMessage(mail_template.subject, message.render(
# 					Context({'user': user})), to=[to_mail])
# 			email.send()
# 			return HttpResponseRedirect('/')
# 	else:
# 		form = SignupForm()

# 	return render(request, 'eshopper/search.html', {'form': form})


def product_list(request, category_slug=None):
	
	category = None
	categories = Category.objects.all()
	products = Product.objects.filter(available=True)
	
	if category_slug:
		category = get_object_or_404(Category, slug=category_slug)
		products = products.filter(category=category)
	return render(request, 'eshopper/list.html', 
				 {'category': category, 
				  'categories': categories, 
				  'products':products}) 


def product_detail(request, id, slug):
	
	product = get_object_or_404(Product, id=id, slug=slug, 
								available=True)
	category = None
	categories = Category.objects.all()
	cart_product_form = CartAddProductForm()
	return render(request, 'eshopper/detail.html', 
				 {'product': product, 
				  'category': category, 
				  'categories': categories,
				  'cart_product_form': cart_product_form})


@require_POST
def cart_add(request, product_id):
	
	cart = Cart(request)
	product = get_object_or_404(Product, id=product_id)
	form = CartAddProductForm(request.POST)
	
	if form.is_valid():
		cd = form.cleaned_data
		cart.add(product=product, quantity=cd['quantity'], 
				 update_quantity=cd['update'])
	return redirect('eshopper:cart_detail') 

def cart_remove(request, product_id):
	
	cart = Cart(request)
	product = get_object_or_404(Product, id=product_id)
	cart.remove(product)
	return redirect('eshopper:cart_detail')

def cart_detail(request):
	
	cart = Cart(request)
	for item in cart:
		item['update_quantity_form'] = CartAddProductForm(initial={
		'quantity': item['quantity'],'update' : True})
	coupon_apply_form = CouponApplyForm()
		
	return render(request, 'eshopper/cart_detail.html', {'cart': cart,
														 'coupon_apply_form': coupon_apply_form})



def contact(request):
	
	if request.method == "POST":
		form = ContactForm(request.POST)
		
		if form.is_valid():
			name = form.cleaned_data['name']
			email = form.cleaned_data['email']
			message = form.cleaned_data['message']
			user = Contact_us(name=name, email=email, 
							  message=message)
			user.save()
			messages.success(request,'message submission sucessful')
			

	form = ContactForm()        
	return render(request, 'eshopper/contact.html', 
				 {'form': form})

@require_POST
def coupon_apply(request):
  	
	now = timezone.now()

	form = CouponApplyForm(request.POST)
	if form.is_valid():
		code = form.cleaned_data['code']
		try:
			coupon = Coupon.objects.get(code__iexact=code,
										valid_from__lte=now,
										valid_to__gte=now,
										active=True)
			request.session['coupon_id'] = coupon.id
			messages.success(request, 'Coupon applied sucessfully.')
		except Coupon.DoesNotExist:
			request.session['coupon_id'] = None

	return redirect('eshopper:cart_detail')        

def coupon_remove(request):

	del request.session['coupon_id']
	return redirect('eshopper:cart_detail')

def order_create(request):
	
	cart = Cart(request)
	if request.method == "POST":
		form = OrderCreateForm(request.POST)
		if form.is_valid():
			if request.user.is_authenticated:
				order = form.save(commit=False)
				if  cart.coupon:
					order.coupon = cart.coupon	
					order.discount = cart.coupon.discount
					order.user = request.user
				order.save()

			else:
				return HttpResponseRedirect('/login')
			for item in cart:
				Order_details.objects.create(order=order,
											 product=item['product'],
											 price=item['price'],
											 quantity=item['quantity'])
			cart.clear()
			request.session['order_id'] = order.id
			return redirect(reverse('payment:process'))
			
	else:
		form =  OrderCreateForm()
	return render(request, 'eshopper/create_order.html', {'cart': cart,'form' : form})                                             





def search(request):
	search_query = request.GET.get('search', None)
	if request.method == 'GET':
		category = None
		categories = Category.objects.all()
		try:
			products = Product.objects.filter(name__icontains=search_query,available=True)
		except Product.DoesNotExist:
			products = None	
	return render(request, 'eshopper/list.html', 
				 {'category': category, 
				  'categories': categories, 
				  'products':products}) 


def signup(request):
	
	if request.method == 'POST':
		if request.POST.get('submit') == 'signup':
			form = SignupForm(request.POST)
			if form.is_valid():
			
				username = form.cleaned_data['username']
				email = form.cleaned_data['email']
				password = form.cleaned_data['password1']
				user = User(username=username, email=email)
				user.set_password(password)
				user.save()
			
				current_site = get_current_site(request)
				mail_template = Email_template.objects.get(title='Registration')
				message = Template(mail_template.content)
			
				to_mail = form.cleaned_data.get('email')
				email = EmailMessage(mail_template.subject, message.render(
					Context({'user': user})), to=[to_mail])
				email.send()
				return HttpResponseRedirect('/')
		elif request.POST.get('submit') == 'login':
			redirect('login')
	else:
		form1 = SignupForm()
		
	return render(request, 'eshopper/search.html', {'form': form1})
		

eshopper/templates/eshopper/acc_active_email.html
{% autoescape off %}

Hi {{ user.username }}

You have been successfully registered.
{% endautoescape %} 

eshopper/templates/eshopper/cart_detail.html
{% extends "eshopper/base.html" %}

{% load static %}

{% block title %}
	Your shopping cart 
{% endblock title %}


{% block content %}
{% if cart %}
<section id="cart_items">
 <div class="container">
  <div class="breadcrumbs">
   <ol class="breadcrumb">
	<li><a href="/">Home</a></li>
	<li class="active">Shopping Cart</li>
   </ol>
  </div>
  <div class="table-responsive cart_info">
   <table class="table table-condensed">
   	<thead>
	 <tr class="cart_menu">
	  <td class="image">Item</td>
	  <td class="description"></td>
	  <td class="price">Price</td>
	  <td class="quantity">Quantity</td>
	  <td class="price">Total</td>
	  <td class="cart_delete"></td>
	 </tr>
	</thead>
	<tbody>
	{% for item in cart %}
	 {% with product=item.product %}
	  <tr>
	   <td class="cart_product">
	    <a href="{{ product.get_absolute_url }}">
		 {% if product.get_product_images %}
	  	 <img src="{{ product.get_product_images.0.image.url }}" height="85" width='83'>
	  	 {% else %}
	     <img src="{% static 'images/404/404.png' %}" height="85" width='83'>
	     {% endif %}
		</a>
	   </td>
	   <td class="cart_description">
	   	<h4>{{ product.name }}</h4>
	   	<p>Web ID:{{ product.id }}</p>
	   </td>
	   <td class="cart_price"><p>${{ item.price }}</p></td>
	   <td class="cart_quantity">
		<div class="cart_quantity_button">
		 <div class="input-group">
		 	<span class="input-group-btn">
		   <form id="myform" action="{% url 'eshopper:cart_add' product.id %}" method='post'>
		   <a style='cursor: pointer;' class='cart_quantity_down' onclick="decreaseValue(event)" value='Decrease value'>-</a>
		   <input class="cart_quantity_input" type="text" name="quantity" id="quantity" value="{{ item.quantity }}" autocomplete="off" size="2">
		   <a style='cursor: pointer;' class='cart_quantity_up' onclick="increaseValue(event)" value='Increase value'>+</a>
		    {{ item.update_quantity_form.update }}
		    {% csrf_token %}
		   </form>
		   </span>
		</div>
		</div>
	   </td>
	   
	   <td class="cart_total">
	   	<p class="cart_total_price">${{ item.total_price }}</p></td>
	   <td class="cart_delete"><a class="cart_quantity_delete" href="{% url 'eshopper:cart_remove' product.id %}"><i class="fa fa-times"></i></a></td>
	  </tr>
	 {% endwith %}
	{% endfor %}
    </tbody>
   </table>
  </div>
</div>
</section>   
<section id="do_action">
   	<div class="container">
   		<div class="heading">
				<h3>What would you like to do next?</h3>
				<p>Choose if you have a discount code you want to use.</p>
		</div>
   <div class='row'>	
   <div class="col-sm-6">
   	
   	<div class="chose_area">
	 <ul class="user_option">
	 
	{% if messages %}
		<li class="messages">
    	{% for message in messages %}
    	<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    	{% endfor %}
		</li>
	{% else %}
	 	{% if request.session.coupon_id %}
	 		<p>Coupon applied sucessfully.</p>	
		{% else %}
		<li>
	  	{% if form.errors %}
	  	<p>{{ form.errors }}</p>
	  	{% endif %}
	     <form action="{% url 'eshopper:apply' %}" method="post">
	     
	     <label>Use Coupon Code</label>
	     {% for field in coupon_apply_form %}
      		<p>
        		{{ field.label_tag }}<br>
        		{{ field }}
        
      		</p>
      	 {% endfor %}
	     <input class="btn btn-default check_out" type="submit" value='Continue' name="">
   		 {% csrf_token %}
   		 </form>
	  	</li>
	  	{% endif %}
	 {% endif %}
	 </ul>
						
	<!-- <a class="btn btn-default update" href="">Get Quotes</a>
	<a class="btn btn-default check_out" href="">Continue</a>
	</div>
   	<table>
   		<tbody>
   	{% if cart.coupon %}
		<tr>
			<td>Subtotal</td>
			<td colspan="4"></td>
			<td>${{ cart.get_total_price }}</td>
		</tr>
		<tr>
			{% with code=cart.coupon.code discount=cart.coupon.discount %}
			<td>{{ code }} coupon ({{ discount }}% off)</td>
			{% endwith %}
			<td colspan="4"></td>
			<td>${{ cart.get_discount|floatformat:'2' }}</td>
		</tr>
	{% endif %}
	<tr>
		<td>Total</td>
		<td colspan="4"></td>
		<td>${{ cart.get_total_price_after_discount|floatformat:'2' }}</td>
	</tr>	
    </tbody>
   </table>

   <p> Apply a coupon:</p>
   <form action="{% url 'eshopper:apply' %}" method="post">
   	{{ coupon_apply_form }}
   	<input type="submit" value='Apply' name="">
   	{% csrf_token %}
   </form> -->
   </div>

  </div>

   <div class="col-sm-6">
	<div class="total_area">
	 <ul>
	  <li>Cart Sub Total <span>${{ cart.get_total_price }}</span></li>
	  <li>Eco Tax <span>$2</span></li>
	  {% if cart.coupon %}
	  <li>{{ cart.coupon.discount }}% off coupon
      <span>${{ cart.get_discount|floatformat:'2'}}</span>
      <td class="cart_delete"><a class="cart_quantity_delete" href="{% url 'eshopper:coupon_remove' %}"><i class="fa fa-times"></i></a></td>
	  </li>
	  {% endif %}	
	  <li>Total<span>${{ cart.get_total_price_with_tax }}</span></li>
	 </ul> 	
		
	<button form="myform" type='submit' class="btn btn-default check_out" style="margin-left: 40px">Update</button>
	{% if cart %}
	<a class="btn btn-default check_out" href="{% if user.is_authenticated %}{% url 'eshopper:order_create' %}{% else %}
	{% url 'eshopper:login' %}{% endif %}" class='button'>Checkout</a>
	{% else %}
	<a class="btn btn-default check_out" href="{% url 'eshopper:product_list' %}" class='button-right'>Continue</a>
	{% endif %}
	 
   </div>
   </div>
</div>
  </div>
 </section>
{% else %}
<div style="position: center;">
<img src="{% static 'images/empty_cart.jpeg' %}">
<p><strong>Your cart is empty</strong></p>
</div>
{% endif %}
{% endblock %}


{% block extra_js %}
	{{block.super}}			
	<script>
		function increaseValue(ev) {
			ev.preventDefault();
		 	var value = parseInt(document.getElementById('quantity').value,10);
		 	value = isNaN(value) ? 0 : value ;
		 	value++;
		 	document.getElementById('quantity').value = value;
		}	

		function decreaseValue(ev){
			ev.preventDefault();
		 	var value = parseInt(document.getElementById('quantity').value,10);
		 	value = isNaN(value) ? 0 : value ;
		 	value < 1 ? value = 1 : '';
		 	value--;
		 	document.getElementById('quantity').value = value;
		}
	</script>
{% endblock %}

eshopper/templates/eshopper/create_order.html
{% extends "eshopper/base.html" %}

{% load static %}

{% block content %}
<section id="cart_items">
		<div class="container">
			<div class="breadcrumbs">
				<ol class="breadcrumb">
				  <li><a href="#">Home</a></li>
				  <li class="active">Check out</li>
				</ol>
			</div>
	<h1>{{ request.user.username }}</h1>
<h3>Your Order</h3>

	
	<!-- <form action="." method="post" class="order-form"> -->
		<!-- 
		{% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="display: none">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
      {% endfor %} -->



      <div class="step-one">
				<h2 class="heading">Step1</h2>
			</div>
			<div class="shopper-informations">
				<div class="row">
				 <div class="col-sm-5 clearfix">
					<div class="form-two">
					 <form action="." method="post" class="order-form">
					  <input type="text"  name='address' placeholder="Address *">
					  <p>{{ form.errors.address }}</p>
					  <input type="text" name='city' placeholder="City">
					  <p>{{ form.errors.city }}</p>
					  <input type="text" name='state' placeholder="State *">
					  <p>{{ form.errors.state }}</p>
					  <input type="text" name='country' placeholder="Country">
					  <p>{{ form.errors.country }}</p>
					  <input type="text" name='zipcode' placeholder="Zipcode">
					  <p>{{ form.errors.zipcode }}</p>
					   {% if cart %}
						<p><input type="submit" class="btn btn-default check_out" style="margin-left:15px;margin-top:0px;" value="Continue" name=""></p>
					  {% else %}
						<a class="btn btn-default check_out" href="{% url 'eshopper:cart_add' %}" class='button'>Add the products</a>
					  {% endif %}
					  {% csrf_token %}
										
					</div>
				</div>

			    <div class="col-sm-4">
			    <div class="order-message">
				 <p>Shipping Order</p>
				 <textarea name="message"  placeholder="Notes about your order, Special Notes for Delivery" rows="16"></textarea>
				 <!-- <label><input type="checkbox"> Shipping to bill address</label> -->
				</form>
				</div>	
			    </div>

			</div>
		</div>


<!-- {% if cart %}
	<a class="btn btn-default check_out" href="{% url 'eshopper:order_create' %}" class='button'>Checkout</a>
	{% endif %} -->
	
 	<div class="review-payment">
  		<h2>Review & Payment</h2>
    </div>
    <div class="table-responsive cart_info">
     <table class="table table-condensed">
   	  <thead>
	   <tr class="cart_menu">
	    <td class="image">Item</td>
	    <td class="description"></td>
	    <td class="price">Price</td>
	    <td class="quantity">Quantity</td>
	    <td class="price">Total</td>
	    <td class="cart_delete"></td>
	   </tr>
	  </thead>
	  <tbody>
	  {% for item in cart %}
	  {% with product=item.product %}
	   <tr>
	    <td class="cart_product">
	     <a href="{{ product.get_absolute_url }}">
		  {% if product.get_product_images %}
	  	  <img src="{{ product.get_product_images.0.image.url }}" height="85" width='83'>
	  	  {% else %}
	      <img src="{% static 'images/404/404.png' %}" height="85" width='83'>
	      {% endif %}
		 </a>
	    </td>
	    <td class="cart_description">
	   	 <h4>{{ product.name }}</h4>
	   	 <p>Web ID:{{ product.id }}</p>
	    </td>
	    <td class="cart_price"><p>${{ item.price }}</p></td>
	    <td class="cart_quantity">
		<div class="cart_quantity_button">
		 <div class="input-group">
		  <span class="input-group-btn">
		   
		   
		   <a class='cart_quantity_down' onclick="decreaseValue(event)" value='Decrease value'>-</a>
		   <input class="cart_quantity_input" type="text" name="quantity" id="quantity" value="{{ item.quantity }}" autocomplete="off" size="2">
		   <a class='cart_quantity_up' onclick="increaseValue(event)" value='Increase value'>+</a>
		  
		  
		 
		  </span>
		 </div>
	    </div>
	    </td>
	    <td class="cart_total">
	   	 <p class="cart_total_price">${{ item.total_price }}</p></td>
	    <td class="cart_delete"><a class="cart_quantity_delete" href="{% url 'eshopper:cart_remove' product.id %}"><i class="fa fa-times"></i></a></td>
	   </tr>
	   {% endwith %}
	   {% endfor %}
	   <tr>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td colsapn="2">
		 <table class="table table-condensed total-result">
		  <tr>
			<td>Cart Sub Total </td>
			<td>${{ cart.get_total_price }}</td>
		  </tr>
		  <tr>
		    <td>Eco Tax </td>
			<td>$2</td>
		  </tr>
		  <tr class="shipping-cost">
			<td>Shipping cost</td>
			<td>Free</td>
		  </tr>
		  {% if cart.coupon %}
		  <tr>
		  	<td>{{ cart.coupon.discount }}% off coupon</td>
		  	<td>${{ cart.get_discount|floatformat:'2'}}</td>
		  </tr>
		  {% endif %}
		  <tr>
			<td>Total</td>
			<td><span>${{ cart.get_total_price_with_tax|floatformat:'2' }}</span></td>
		  </tr>
		 </table>
		</td>
	   </tr>
    </tbody>
   </table>
  </div>
{% endblock %} 	

eshopper/templates/eshopper/detail.html
{% extends "eshopper/base.html" %}

{% load static %}




{% block content %}
<section>
 <div class="container">
  <div class="row">
   <div class="col-sm-3">
	<div class="left-sidebar">
	 <h2>Category</h2>
	  <div class="panel-group category-products" id="accordian">
	   {% for c in categories %}
		<div class="panel panel-default">
		 <div class="panel-heading">
		  <h4 class="panel-title"> 
		{% if category.slug == c.slug %}
		{% endif %}
		   <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
		  </h4>
		 </div>
		</div>
	   {% endfor %}
	  </div>
	</div>
   </div>
   <div class="col-sm-9 padding-right">
	<div class="product-details"><!--product-details-->
	 <div class="col-sm-5">
	  <div class="view-product">
	  {% if product.get_product_images %}
	  <img src="{{ product.get_product_images.1.image.url }}">
	  {% else %}
	  <img src="{% static 'images/404/404.png' %}">
	  {% endif %}
	  <!-- <h3>ZOOM</h3> -->
	  </div>
	 </div>
	 <div class="col-sm-7">
	  <div class="product-information"><!--/product-information-->
	   <img src="{% static 'images/product-details/new.jpg' %}" class="newarrival" alt="" />
	   
	   <h2>{{ product.name }}</h2>
	   <p>Web ID: {{ product.id }}</p>
	   <img src="{% static 'images/product-details/rating.png' %}" alt="" />

	    <span>
			<span>US ${{ product.price }}</span>
	   		<fieldset>	
	   		<form action="{% url 'eshopper:cart_add' product.id %}" method="post">
	   		<label for="quantity">Quantity:</label>
	   		<input name='quantity'>	 	
	   		{{ cart_product_form.update }}
		 	<button type="submit" class="btn btn-default cart">
			<i class="fa fa-shopping-cart"></i> Add to cart</button>
			{% csrf_token %}
			</form>
		 	</fieldset>		
		</span>
	   <p><b>Availability:</b> In Stock</p>
	   <p><b>Condition:</b> New</p>
	   <p><b>Brand:</b> E-SHOPPER</p>
	   <!-- <p><b>Description:</b>{{ product.short_description|linebreaks }}</p> -->
	   <a href=""><img src="{% static 'images/product-details/share.png' %}" class="share img-responsive"  alt="" /></a>
	  </div><!--/product-information-->
	 </div>
	<!--/product-details-->
   </div>
  </div>
 </div>
</div>
</section>

{% endblock content %}	

eshopper/templates/eshopper/login.html
{% extends 'eshopper/base.html' %}
{% block title %}Login{% endblock title %}

{% block content %}
<section id="form"><!--form-->
 <div class="container">
  <div class="row">
   <div class="col-sm-4 col-sm-offset-1">

    <div class="login-form">
     <h2>Login to your account</h2>
     <form method="post" action="{% url 'eshopper:login' %}">
     {% csrf_token %}
     {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="display: none">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
      {% endfor %}
     
     <button type="submit" class="btn btn-default">Login</button>
     <input type="hidden" name="next" value="{{ next }}" />
    </form>
    <div class="center-text">
    <div>
	 <h3 class="or">OR</h3>
	</div>
	<div class="col-sm-4">
	<a class="btn btn-default" href="{% url 'eshopper:signup' %}" class='button'> Go for Signup</a>
	</div>
    </div>
   </div>
  </div>
 </div>
</div>
</section>
{% endblock content %}